global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "1m"
  body_size_limit: "0"
  sample_limit: 0
  label_limit: 0
  label_name_length_limit: 0
  label_value_length_limit: 0
  target_limit: 0

scrape_configs:
  - job_name: "node-app"
    static_configs:
      - targets: ["host.docker.internal:3000"]
# host.docker.internal allows Docker (Prometheus container) to reach your local machine's port from inside the container (works on Windows/Mac).

